# aroya_air/data.py
# -----------------------------------------------------------------------------
# This module now generates a richer flight schedule from a curated set of base
# routes.  The project previously shipped with fewer than a dozen services,
# which limited search variety.  We keep the structure identical (list of
# flights) so the rest of the codebase keeps working as-is.

from __future__ import annotations

import os
from datetime import date, datetime, timedelta
from typing import Any, Dict, Iterable, List, Optional

# Anchor schedule generation to "today" so older departures are discarded.
# Keep this in sync with consts.CURRENT_DATE_OVERRIDE and utils.DATE_OVERRIDE.
def _resolve_start_date() -> date:
    env_today = os.getenv("AROYA_TODAY")
    if env_today:
        try:
            return datetime.fromisoformat(env_today).date()
        except ValueError:
            pass
    return date.today()


REFERENCE_START_DATE = _resolve_start_date()


def _align_to_start(
    dep_base: datetime,
    arr_base: datetime,
    start_date: date,
) -> tuple[datetime, datetime]:
    """
    Shift the base departure/arrival forward so the first generated flight
    cannot fall before the configured start date (today).
    """
    if dep_base.date() >= start_date:
        return dep_base, arr_base

    delta = timedelta(days=(start_date - dep_base.date()).days)
    return dep_base + delta, arr_base + delta


def _generate_schedule(
    routes: Iterable[Dict[str, Any]],
    flights_per_route: int = 5,
    start_date: Optional[date] = None,
) -> List[Dict[str, Any]]:
    """Expand every base route into multiple dated services.

    The generator keeps IDs, numbers, pricing, and seat inventory deterministic
    so tests remain stable while the live assistant benefits from many more
    options for searching, comparisons, and booking.
    """

    flights: List[Dict[str, Any]] = []
    start = start_date or REFERENCE_START_DATE

    for route in routes:
        dep_base_raw = datetime.fromisoformat(route["departure_time"])
        arr_base_raw = datetime.fromisoformat(route["arrival_time"])
        dep_base, arr_base = _align_to_start(dep_base_raw, arr_base_raw, start)

        status_sequence = route.get("status_sequence") or [route.get("status", "On Time")]
        price_step = route.get("price_step", 0.0)
        seat_decrement = route.get("seat_decrement", 1)
        min_seats = route.get("min_seats", 2)
        interval_days = route.get("interval_days", 3)
        number_padding = route.get("flight_number_padding", 0)

        for idx in range(flights_per_route):
            offset = timedelta(days=idx * interval_days)
            departure_time = (dep_base + offset).isoformat()
            arrival_time = (arr_base + offset).isoformat()

            numeric = route["flight_number_start"] + idx
            if number_padding:
                flight_number = f"{route['flight_number_prefix']}{numeric:0{number_padding}d}"
            else:
                flight_number = f"{route['flight_number_prefix']}{numeric}"

            price = round(route["price_usd"] + price_step * idx, 2)
            seats_remaining = route["seats_available"] - seat_decrement * idx
            seats_available = max(min_seats, seats_remaining)

            flight = {
                "flight_id": f"{route['flight_id_prefix']}{idx + 1:02d}",
                "airline": route["airline"],
                "flight_number": flight_number,
                "departure_city": route["departure_city"],
                "arrival_city": route["arrival_city"],
                "departure_airport": route["departure_airport"],
                "arrival_airport": route["arrival_airport"],
                "departure_airport_code": route["departure_airport_code"],
                "arrival_airport_code": route["arrival_airport_code"],
                "departure_time": departure_time,
                "arrival_time": arrival_time,
                "duration": route["duration"],
                "aircraft_type": route["aircraft_type"],
                "baggage_allowance": route["baggage_allowance"],
                "available_classes": route["available_classes"],
                "price_usd": price,
                "seats_available": seats_available,
                "wifi_available": route["wifi_available"],
                "inflight_entertainment": route["inflight_entertainment"],
                "status": status_sequence[idx % len(status_sequence)],
            }
            flights.append(flight)

    flights.sort(key=lambda entry: entry["departure_time"])
    return flights


# -----------------------------------------------------------------------------#
# Base route templates (kept human-readable for easy curation)

BASE_ROUTES: List[Dict[str, Any]] = [
    {
        "flight_id_prefix": "QR979",
        "airline": "Qatar Airways",
        "flight_number_prefix": "QR",
        "flight_number_start": 979,
        "flight_number_padding": 3,
        "departure_city": "Toronto",
        "arrival_city": "Singapore",
        "departure_airport": "Toronto Pearson International Airport",
        "arrival_airport": "Singapore Changi Airport",
        "departure_airport_code": "YYZ",
        "arrival_airport_code": "SIN",
        "departure_time": "2025-11-26T22:00:00-05:00",
        "arrival_time": "2025-11-27T18:00:00+08:00",
        "duration": "19h 0m",
        "aircraft_type": "Airbus A380-800",
        "baggage_allowance": "25kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1077.86,
        "price_step": 42.5,
        "seats_available": 30,
        "seat_decrement": 3,
        "min_seats": 6,
        "interval_days": 4,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "UA664",
        "airline": "United Airlines",
        "flight_number_prefix": "UA",
        "flight_number_start": 664,
        "flight_number_padding": 3,
        "departure_city": "London",
        "arrival_city": "Jeddah",
        "departure_airport": "Heathrow Airport",
        "arrival_airport": "King Abdulaziz International Airport",
        "departure_airport_code": "LHR",
        "arrival_airport_code": "JED",
        "departure_time": "2025-11-05T20:30:00+00:00",
        "arrival_time": "2025-11-06T03:15:00+03:00",
        "duration": "6h 45m",
        "aircraft_type": "Airbus A320neo",
        "baggage_allowance": "23kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 986.40,
        "price_step": 31.25,
        "seats_available": 38,
        "seat_decrement": 4,
        "min_seats": 10,
        "interval_days": 5,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "Cancelled", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "SQ617",
        "airline": "Singapore Airlines",
        "flight_number_prefix": "SQ",
        "flight_number_start": 617,
        "flight_number_padding": 3,
        "departure_city": "Hong Kong",
        "arrival_city": "Mumbai",
        "departure_airport": "Hong Kong International Airport",
        "arrival_airport": "Chhatrapati Shivaji Maharaj International Airport",
        "departure_airport_code": "HKG",
        "arrival_airport_code": "BOM",
        "departure_time": "2025-11-07T22:30:00+08:00",
        "arrival_time": "2025-11-08T00:30:00+05:30",
        "duration": "6h 30m",
        "aircraft_type": "Airbus A380-800",
        "baggage_allowance": "30kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 1115.69,
        "price_step": 24.9,
        "seats_available": 28,
        "seat_decrement": 2,
        "min_seats": 6,
        "interval_days": 3,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "Delayed", "On Time", "On Time", "Cancelled"],
    },
    {
        "flight_id_prefix": "DL919",
        "airline": "Delta Air Lines",
        "flight_number_prefix": "DL",
        "flight_number_start": 919,
        "flight_number_padding": 3,
        "departure_city": "Sydney",
        "arrival_city": "Toronto",
        "departure_airport": "Sydney Kingsford Smith Airport",
        "arrival_airport": "Toronto Pearson International Airport",
        "departure_airport_code": "SYD",
        "arrival_airport_code": "YYZ",
        "departure_time": "2025-11-28T13:15:00+10:00",
        "arrival_time": "2025-11-28T02:30:00-05:00",
        "duration": "17h 15m",
        "aircraft_type": "Boeing 787-9",
        "baggage_allowance": "23kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 1798.84,
        "price_step": 55.0,
        "seats_available": 26,
        "seat_decrement": 3,
        "min_seats": 8,
        "interval_days": 6,
        "wifi_available": False,
        "inflight_entertainment": True,
        "status_sequence": ["Delayed", "On Time", "On Time", "Delayed", "On Time"],
    },
    {
        "flight_id_prefix": "CX891",
        "airline": "Cathay Pacific",
        "flight_number_prefix": "CX",
        "flight_number_start": 891,
        "flight_number_padding": 3,
        "departure_city": "Hong Kong",
        "arrival_city": "Dubai",
        "departure_airport": "Hong Kong International Airport",
        "arrival_airport": "Dubai International Airport",
        "departure_airport_code": "HKG",
        "arrival_airport_code": "DXB",
        "departure_time": "2025-11-07T12:30:00+08:00",
        "arrival_time": "2025-11-07T13:30:00+04:00",
        "duration": "8h 0m",
        "aircraft_type": "Airbus A320",
        "baggage_allowance": "25kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 671.74,
        "price_step": 18.5,
        "seats_available": 35,
        "seat_decrement": 4,
        "min_seats": 10,
        "interval_days": 3,
        "wifi_available": True,
        "inflight_entertainment": False,
        "status_sequence": ["Delayed", "On Time", "On Time", "On Time", "Delayed"],
    },
    {
        "flight_id_prefix": "SQ415",
        "airline": "Singapore Airlines",
        "flight_number_prefix": "SQ",
        "flight_number_start": 415,
        "flight_number_padding": 3,
        "departure_city": "Cairo",
        "arrival_city": "Amsterdam",
        "departure_airport": "Cairo International Airport",
        "arrival_airport": "Amsterdam Airport Schiphol",
        "departure_airport_code": "CAI",
        "arrival_airport_code": "AMS",
        "departure_time": "2025-11-18T04:45:00+02:00",
        "arrival_time": "2025-11-18T06:45:00+01:00",
        "duration": "5h 0m",
        "aircraft_type": "Airbus A350-900",
        "baggage_allowance": "20kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 853.06,
        "price_step": 22.0,
        "seats_available": 18,
        "seat_decrement": 2,
        "min_seats": 5,
        "interval_days": 4,
        "wifi_available": True,
        "inflight_entertainment": False,
        "status_sequence": ["Landed", "On Time", "On Time", "On Time", "Delayed"],
    },
    {
        "flight_id_prefix": "SQ453",
        "airline": "Singapore Airlines",
        "flight_number_prefix": "SQ",
        "flight_number_start": 453,
        "flight_number_padding": 3,
        "departure_city": "Hong Kong",
        "arrival_city": "Tokyo",
        "departure_airport": "Hong Kong International Airport",
        "arrival_airport": "Narita International Airport",
        "departure_airport_code": "HKG",
        "arrival_airport_code": "NRT",
        "departure_time": "2025-11-09T01:00:00+08:00",
        "arrival_time": "2025-11-09T12:45:00+09:00",
        "duration": "11h 45m",
        "aircraft_type": "Boeing 737 MAX 8",
        "baggage_allowance": "15kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1624.52,
        "price_step": 35.0,
        "seats_available": 24,
        "seat_decrement": 3,
        "min_seats": 9,
        "interval_days": 3,
        "wifi_available": True,
        "inflight_entertainment": False,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "QF171",
        "airline": "Qantas",
        "flight_number_prefix": "QF",
        "flight_number_start": 171,
        "flight_number_padding": 3,
        "departure_city": "Istanbul",
        "arrival_city": "Paris",
        "departure_airport": "Istanbul Airport",
        "arrival_airport": "Charles de Gaulle Airport",
        "departure_airport_code": "IST",
        "arrival_airport_code": "CDG",
        "departure_time": "2025-11-14T00:15:00+03:00",
        "arrival_time": "2025-11-14T05:00:00+01:00",
        "duration": "6h 45m",
        "aircraft_type": "Airbus A380-800",
        "baggage_allowance": "15kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 2091.61,
        "price_step": 28.75,
        "seats_available": 30,
        "seat_decrement": 3,
        "min_seats": 8,
        "interval_days": 4,
        "wifi_available": False,
        "inflight_entertainment": False,
        "status_sequence": ["Cancelled", "On Time", "On Time", "Delayed", "On Time"],
    },
    {
        "flight_id_prefix": "AF780",
        "airline": "Air France",
        "flight_number_prefix": "AF",
        "flight_number_start": 780,
        "flight_number_padding": 3,
        "departure_city": "Doha",
        "arrival_city": "Singapore",
        "departure_airport": "Hamad International Airport",
        "arrival_airport": "Singapore Changi Airport",
        "departure_airport_code": "DOH",
        "arrival_airport_code": "SIN",
        "departure_time": "2025-11-23T09:15:00+03:00",
        "arrival_time": "2025-11-23T19:00:00+08:00",
        "duration": "7h 45m",
        "aircraft_type": "Boeing 787-9",
        "baggage_allowance": "30kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 2073.57,
        "price_step": 27.95,
        "seats_available": 22,
        "seat_decrement": 2,
        "min_seats": 6,
        "interval_days": 5,
        "wifi_available": True,
        "inflight_entertainment": False,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "EY552",
        "airline": "Etihad Airways",
        "flight_number_prefix": "EY",
        "flight_number_start": 552,
        "flight_number_padding": 3,
        "departure_city": "London",
        "arrival_city": "Tokyo",
        "departure_airport": "Heathrow Airport",
        "arrival_airport": "Narita International Airport",
        "departure_airport_code": "LHR",
        "arrival_airport_code": "NRT",
        "departure_time": "2025-11-14T18:30:00+00:00",
        "arrival_time": "2025-11-15T12:15:00+09:00",
        "duration": "14h 45m",
        "aircraft_type": "Airbus A350-1000",
        "baggage_allowance": "20kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1512.33,
        "price_step": 33.4,
        "seats_available": 28,
        "seat_decrement": 2,
        "min_seats": 8,
        "interval_days": 6,
        "wifi_available": False,
        "inflight_entertainment": False,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "EK202",
        "airline": "Emirates",
        "flight_number_prefix": "EK",
        "flight_number_start": 202,
        "flight_number_padding": 3,
        "departure_city": "New York",
        "arrival_city": "Dubai",
        "departure_airport": "John F. Kennedy International Airport",
        "arrival_airport": "Dubai International Airport",
        "departure_airport_code": "JFK",
        "arrival_airport_code": "DXB",
        "departure_time": "2025-11-09T09:30:00-05:00",
        "arrival_time": "2025-11-10T18:30:00+04:00",
        "duration": "12h 30m",
        "aircraft_type": "Airbus A380-800",
        "baggage_allowance": "30kg + 10kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1845.25,
        "price_step": 45.0,
        "seats_available": 42,
        "seat_decrement": 4,
        "min_seats": 12,
        "interval_days": 3,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "Delayed", "On Time", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "LH456",
        "airline": "Lufthansa",
        "flight_number_prefix": "LH",
        "flight_number_start": 456,
        "flight_number_padding": 3,
        "departure_city": "Frankfurt",
        "arrival_city": "Los Angeles",
        "departure_airport": "Frankfurt Airport",
        "arrival_airport": "Los Angeles International Airport",
        "departure_airport_code": "FRA",
        "arrival_airport_code": "LAX",
        "departure_time": "2025-11-10T10:20:00+01:00",
        "arrival_time": "2025-11-10T13:30:00-08:00",
        "duration": "12h 10m",
        "aircraft_type": "Boeing 747-8",
        "baggage_allowance": "23kg + 8kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1325.40,
        "price_step": 30.75,
        "seats_available": 36,
        "seat_decrement": 3,
        "min_seats": 10,
        "interval_days": 5,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "On Time", "Delayed", "On Time"],
    },
    {
        "flight_id_prefix": "AA422",
        "airline": "American Airlines",
        "flight_number_prefix": "AA",
        "flight_number_start": 422,
        "flight_number_padding": 3,
        "departure_city": "Dallas",
        "arrival_city": "Miami",
        "departure_airport": "Dallas/Fort Worth International Airport",
        "arrival_airport": "Miami International Airport",
        "departure_airport_code": "DFW",
        "arrival_airport_code": "MIA",
        "departure_time": "2025-11-04T08:15:00-05:00",
        "arrival_time": "2025-11-04T11:30:00-05:00",
        "duration": "3h 15m",
        "aircraft_type": "Boeing 737-800",
        "baggage_allowance": "20kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 325.99,
        "price_step": 12.0,
        "seats_available": 40,
        "seat_decrement": 5,
        "min_seats": 12,
        "interval_days": 2,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "NH184",
        "airline": "All Nippon Airways",
        "flight_number_prefix": "NH",
        "flight_number_start": 184,
        "flight_number_padding": 3,
        "departure_city": "Tokyo",
        "arrival_city": "Honolulu",
        "departure_airport": "Tokyo Haneda Airport",
        "arrival_airport": "Daniel K. Inouye International Airport",
        "departure_airport_code": "HND",
        "arrival_airport_code": "HNL",
        "departure_time": "2025-11-12T21:30:00+09:00",
        "arrival_time": "2025-11-12T09:15:00-10:00",
        "duration": "7h 45m",
        "aircraft_type": "Boeing 787-10",
        "baggage_allowance": "23kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1188.60,
        "price_step": 27.4,
        "seats_available": 34,
        "seat_decrement": 3,
        "min_seats": 9,
        "interval_days": 4,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "Delayed", "On Time", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "AI102",
        "airline": "Air India",
        "flight_number_prefix": "AI",
        "flight_number_start": 102,
        "flight_number_padding": 3,
        "departure_city": "Delhi",
        "arrival_city": "London",
        "departure_airport": "Indira Gandhi International Airport",
        "arrival_airport": "Heathrow Airport",
        "departure_airport_code": "DEL",
        "arrival_airport_code": "LHR",
        "departure_time": "2025-11-16T02:20:00+05:30",
        "arrival_time": "2025-11-16T07:15:00+00:00",
        "duration": "8h 25m",
        "aircraft_type": "Boeing 777-300ER",
        "baggage_allowance": "25kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 924.45,
        "price_step": 21.75,
        "seats_available": 32,
        "seat_decrement": 3,
        "min_seats": 8,
        "interval_days": 4,
        "wifi_available": False,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "BA058",
        "airline": "British Airways",
        "flight_number_prefix": "BA",
        "flight_number_start": 58,
        "flight_number_padding": 3,
        "departure_city": "Johannesburg",
        "arrival_city": "London",
        "departure_airport": "O. R. Tambo International Airport",
        "arrival_airport": "Heathrow Airport",
        "departure_airport_code": "JNB",
        "arrival_airport_code": "LHR",
        "departure_time": "2025-11-08T19:10:00+02:00",
        "arrival_time": "2025-11-09T05:45:00+00:00",
        "duration": "11h 35m",
        "aircraft_type": "Airbus A350-1000",
        "baggage_allowance": "23kg + 7kg",
        "available_classes": ["Economy", "Business", "First"],
        "price_usd": 1345.80,
        "price_step": 29.8,
        "seats_available": 38,
        "seat_decrement": 4,
        "min_seats": 10,
        "interval_days": 5,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "Delayed", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "LA807",
        "airline": "LATAM Airlines",
        "flight_number_prefix": "LA",
        "flight_number_start": 807,
        "flight_number_padding": 3,
        "departure_city": "São Paulo",
        "arrival_city": "Madrid",
        "departure_airport": "São Paulo/Guarulhos International Airport",
        "arrival_airport": "Adolfo Suárez Madrid–Barajas Airport",
        "departure_airport_code": "GRU",
        "arrival_airport_code": "MAD",
        "departure_time": "2025-11-17T23:50:00-03:00",
        "arrival_time": "2025-11-18T14:20:00+01:00",
        "duration": "9h 30m",
        "aircraft_type": "Boeing 777-300ER",
        "baggage_allowance": "23kg + 8kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 998.30,
        "price_step": 23.6,
        "seats_available": 34,
        "seat_decrement": 3,
        "min_seats": 9,
        "interval_days": 4,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "Delayed", "On Time", "On Time", "On Time"],
    },
    {
        "flight_id_prefix": "TK215",
        "airline": "Turkish Airlines",
        "flight_number_prefix": "TK",
        "flight_number_start": 215,
        "flight_number_padding": 3,
        "departure_city": "Singapore",
        "arrival_city": "Istanbul",
        "departure_airport": "Singapore Changi Airport",
        "arrival_airport": "Istanbul Airport",
        "departure_airport_code": "SIN",
        "arrival_airport_code": "IST",
        "departure_time": "2025-11-21T00:45:00+08:00",
        "arrival_time": "2025-11-21T06:15:00+03:00",
        "duration": "11h 30m",
        "aircraft_type": "Airbus A350-900",
        "baggage_allowance": "30kg + 7kg",
        "available_classes": ["Economy", "Business"],
        "price_usd": 1185.70,
        "price_step": 26.2,
        "seats_available": 28,
        "seat_decrement": 2,
        "min_seats": 8,
        "interval_days": 4,
        "wifi_available": True,
        "inflight_entertainment": True,
        "status_sequence": ["On Time", "On Time", "On Time", "Delayed", "On Time"],
    },
]


# Generate a broad, deterministic schedule (~100 flights) starting from 2025-11-26.
GENERATED_FLIGHTS = _generate_schedule(
    BASE_ROUTES,
    flights_per_route=5,
    start_date=REFERENCE_START_DATE,
)

data = {"flights": GENERATED_FLIGHTS}
data_two_rows = {"flights": GENERATED_FLIGHTS[:2]}

# Downstream code imports ACTIVE_DATASET; keep that contract intact.
ACTIVE_DATASET = data

__all__ = [
    "ACTIVE_DATASET",
    "BASE_ROUTES",
    "data",
    "data_two_rows",
]
